version : "3.7"
services:
   mongodb:
      image: mongo:latest
      restart: always
      hostname: mongodb
      ports:
         - 27017:27017
      volumes:
         - ./Database:/data/db
      networks:
         - default-local
   redis:
      image: redis:latest
      restart: always
      hostname: redis
      deploy:
         restart_policy:
            condition: on-failure
            delay: 10s
            max_attempts: 5
            window: 120s
      volumes:
         -/dev/ttyUSB0:/dev/ttyUSB0
      networks:
         - default-local
   webapplication-local:
      build:
         context: ./UI
         dockerfile: Dockerfile_Local
      restart: always
      hostname: webapplication-local
      networks:
         - default-local
      ports:
         - 80:80
   api-local:
      build: ./RestAPI
      hostname: api-local
      restart: always
      privileged: true
      env_file:
         - local.env
      volumes:
         - ./dev-X509-cert.pem:/dev-X509-cert.pem
      ports:
         - 3000:3000
      networks:
         - default-local
networks:
   default-local:
      driver: bridge
