# Stage 1: Build the application
FROM node:20-slim as build-step

# Create and set the working directory
WORKDIR /app

# Copy only the package.json and package-lock.json initially to take advantage of caching
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Build the application for production
RUN npm run build --configuration=local

# Stage 2: Create a lightweight runtime image
FROM nginx:1.25.1-alpine as runtime-image

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built application from the build stage
COPY --from=build-step /app/dist/ui /usr/share/nginx/html/

# Expose the default Nginx port (80)
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
