name: "Docker Image Build"

on: [workflow_call]

jobs:
  Build_RestAPI_Container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image RestAPI
      run: docker build -t api -f ./RestAPI/Dockerfile ./RestAPI
  Build_Webapplication_Container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image for Webapplication
      run: docker build -t ui -f ./UI/Dockerfile_Local ./UI

