name: Deploy to Server for Production

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  Build_images:
    uses: ./.github/workflows/build-docker-images.yml
  Test_Security_Staging:
    uses: ./.github/workflows/Security-Testing-Staging.yml
    needs: [Build_images]
  API_Testing:
   needs: [Test_Security_Staging]
   uses: ./.github/workflows/API-Testing.yml
   secrets: inherit
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [API_Testing]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save SSH private key to a file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem

      - name: Deploy to Server
        run: |
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem git@${{ secrets.SSH_SERVER }} -p 5022 "cd /home/git/Production/POS && docker-compose -p POS_prod down && git pull && docker-compose -p POS_prod up --build -d"
  Test_Security_Prod:
    uses: ./.github/workflows/Security-Testing-Prod.yml
    needs: [deploy-prod]
